### ISSUE TITLE
Docker-Homebridge Update info wrong

### ISSUE THREAD

**Issue by pasqualito79** [oznu/docker-homebridge#645]
### Describe The Bug

since homebridge-UI version 5, the new update info window shows wrong information about the docker-homebridge version (besides it's ugly ui with he dropdown to see the homebridge and ui versions below). 

<img width="928" height="137" alt="Image" src="https://github.com/user-attachments/assets/58f9ca43-cc08-462e-bb7d-6315d0393980" />

I have updated the docker-image several times via the synology container manager, so I'm on the newest version of August, but the ui always shows me the same old version. 

<img width="786" height="253" alt="Image" src="https://github.com/user-attachments/assets/8d7cea54-6a37-4deb-9d62-01e5dcbd79af" />

### Config

```JSON

```

### Homebridge UI Version

v5.4.1

### Homebridge Version

v1.11.0

### Node.js Version

v22.18.0

### Operating System

Synology DSM

### Environment Info

Using Docker

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Can you share a log from starting the docker container?  It should show what is happening

**Comment by pasqualito79** [comment]
HI there, I think this is the one you mean, right? 

<img width="1379" height="659" alt="Image" src="https://github.com/user-attachments/assets/ab7ba5cd-d60b-4349-a6f2-7670dd30f7de" />
there it shows  the correct release version of the docker container, but the one shown in the UI is old (2025-06-29)...

**Comment by NorthernMan54** [comment]
It looks like this issue - https://github.com/portainer/portainer/issues/8835

**Comment by NorthernMan54** [comment]
If you run export from terminal, what do you see ?

```
root@docker-desktop:/var/lib/homebridge $ export
declare -x CONFIG_UI_VERSION="4.44.2"
declare -x DEBIAN_FRONTEND="noninteractive"
declare -x DOCKER_HOMEBRIDGE_VERSION="beta-2025-08-15"
declare -x ENABLE_AVAHI="1"
declare -x FFMPEG_FOR_HOMEBRIDGE_VERSION="v2.1.7"
declare -x HOME="/home/homebridge"
declare -x HOMEBRIDGE_APT_PACKAGE="1"
declare -x HOMEBRIDGE_APT_PKG_VERSION="v1.7.6-beta.20250815"
declare -x HOMEBRIDGE_CONFIG_UI="1"
declare -x HOSTNAME="docker-desktop"
```

**Comment by pasqualito79** [comment]
yep, In export it seems wrong:

root@homebridge:/homebridge $ export                                             
declare -x DEBIAN_FRONTEND="noninteractive"                                      
declare -x DOCKER_HOMEBRIDGE_VERSION="2025-06-29"                                
declare -x ENABLE_AVAHI="1"                                                      
declare -x FFMPEG_FOR_HOMEBRIDGE_VERSION="v2.1.7"                                
declare -x HOME="/home/homebridge"                                               
declare -x HOMEBRIDGE_APT_PACKAGE="1"                                            
declare -x HOMEBRIDGE_APT_PKG_VERSION="v1.4.0"                                   
declare -x HOSTNAME="homebridge"                                                 
declare -x OLDPWD                                                                
declare -x PATH="/opt/homebridge/bin:/var/lib/homebridge/node_modules/.bin:/usr/l
ocal/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"                          
declare -x PWD="/homebridge"                                                     
declare -x S6_CMD_WAIT_FOR_SERVICES_MAXTIME="0"                                  
declare -x S6_KEEP_ENV="1"                                                       
declare -x S6_OVERLAY_VERSION="3.1.1.2"                                          
declare -x SHLVL="1"                                                             
declare -x TERM="xterm"                                                          
declare -x TZ="Europe/Zurich"                                                    
declare -x UIX_CUSTOM_PLUGIN_PATH="/var/lib/homebridge/node_modules"             
declare -x USER="root"                                                           
declare -x npm_config_prefix="/opt/homebridge"                                   
root@homebridge:/homebridge $

**Comment by NorthernMan54** [comment]
Definitely looks the same as the portainer issue, let me change how the DOCKER_HOMEBRIDGE_VERSION is being managed.

**Comment by MRedRaider81** [comment]
Seeing the same issue on Portainer hosted on an N100. Previously worked the last time I updated; Here's the export for reference:
root@ubuntu-raider:/homebridge $ export
declare -x DEBIAN_FRONTEND="noninteractive"
declare -x DOCKER_HOMEBRIDGE_VERSION="2025-07-25"
declare -x ENABLE_AVAHI="1"
declare -x FFMPEG_FOR_HOMEBRIDGE_VERSION="v2.1.7"
declare -x FFMPEG_VERSION="v2.1.7"
declare -x HOME="/home/homebridge"
declare -x HOMEBRIDGE_APT_PACKAGE="1"
declare -x HOMEBRIDGE_APT_PKG_VERSION="v1.3.9"
declare -x HOMEBRIDGE_CONFIG_UI_PORT="8581"
declare -x HOSTNAME="ubuntu-raider"
declare -x LANG="C.UTF-8"
declare -x LC_ALL="C.UTF-8"
declare -x OLDPWD
declare -x PATH="/opt/homebridge/bin:/var/lib/homebridge/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/homebridge"
declare -x S6_CMD_WAIT_FOR_SERVICES_MAXTIME="0"
declare -x S6_KEEP_ENV="1"
declare -x S6_OVERLAY_VERSION="3.1.1.2"
declare -x SHLVL="1"
declare -x TERM="xterm-256color"
declare -x UIX_CUSTOM_PLUGIN_PATH="/var/lib/homebridge/node_modules"
declare -x USER="root"
declare -x npm_config_prefix="/opt/homebridge"

**Comment by NorthernMan54** [comment]
If you could update to the latest release, 2025-08-20, I believe this should be resolved.

**Comment by MRedRaider81** [comment]
Just updated, appears to be addressed for me through Portainer re-create / pull.
Thank you!

**Comment by pasqualito79** [comment]
Yep, works: 

<img width="568" height="130" alt="Image" src="https://github.com/user-attachments/assets/ea8ab25c-256b-4b8e-a5f4-c973a7066a8b" />

Still ugly UI design with the dropdown but that's another thing:

<img width="911" height="117" alt="Image" src="https://github.com/user-attachments/assets/50e0736f-923d-4e4f-8e60-a05fd50d2ddc" />

**Comment by NorthernMan54** [comment]
@pasqualito79 The next release of the UI will maintain the collapsed or expanded state - https://github.com/homebridge/homebridge-config-ui-x/pull/2529

Hopefully this helps with your style concerns

**Comment by pasqualito79** [comment]
Hi @NorthernMan54 

bug is back again with docker version 2025-10-22. 
Shows:
2025-06-29 → 2025-10-22

**Comment by NorthernMan54** [comment]
That's weird as the fix I implemented back in August is still there.

What does export show and what files are in /opt/homebridge

```
ls -l
total 992
-rw-r--r-- 1 root root 762103 Oct 20 17:33 CHANGELOG.md
-rw-r--r-- 1 root root    257 Oct 22 18:42 Docker.manifest
-rw-r--r-- 1 root root 143299 Oct 20 17:33 LICENSE
-rw-r--r-- 1 root root  41705 Oct 20 17:33 README.md
-rwxr-xr-x 1 root root   1092 Oct 22 04:05 bashrc
-rwxr-xr-x 1 root root    118 Oct 22 04:05 bashrc-hb-shell
drwxr-xr-x 2 root root   4096 Oct 22 18:42 bin
-rwxr-xr-x 1 root root   7017 Oct 22 04:05 hb-service-shim
-rwxr-xr-x 1 root root   1210 Oct 22 04:05 hb-shell
-rw-r--r-- 1 root root   2366 Oct 22 04:05 homebridge_apt_pkg_arm64.manifest
drwxr-xr-x 3 root root   4096 Oct 22 18:42 include
drwxr-xr-x 3 root root   4096 Oct 22 18:42 lib
-rw-r--r-- 1 root root    828 Oct 22 04:05 package.json
drwxr-xr-x 4 root root   4096 Oct 22 18:42 share
-rwxr-xr-x 1 root root    132 Oct 22 18:42 source-docker.sh
-rwxr-xr-x 1 root root   1089 Oct 22 18:42 source.sh
-rwxr-xr-x 1 root root   1523 Oct 22 04:05 start.sh
```
I did recently make a change in source.sh....

**Comment by pasqualito79** [comment]
Hello, here you are: 

<img width="653" height="367" alt="Image" src="https://github.com/user-attachments/assets/3624ac2a-1174-4383-9e30-0c88da5d6d06" />

**Comment by pasqualito79** [comment]
<img width="670" height="316" alt="Image" src="https://github.com/user-attachments/assets/fecfe5e3-b308-4a92-b821-fbb0502da086" />

**Comment by NorthernMan54** [comment]
What does the file source-docker.sh contain ?

**Comment by pasqualito79** [comment]
<img width="420" height="96" alt="Image" src="https://github.com/user-attachments/assets/06bac902-dfc8-4f03-a739-6957f32b5e45" />

**Comment by NorthernMan54** [comment]
And source.sh - I fixed a bug a few days ago with source.sh

Am wondering if that is breaking this

**Comment by pasqualito79** [comment]
here your go:

<img width="659" height="572" alt="Image" src="https://github.com/user-attachments/assets/33d492e4-6867-4bc2-890b-29d3d2461233" />

**Comment by NorthernMan54** [comment]
Yeah that last line gives an error - fixed in the next release.  If you run 

```bash
. /opt/homebridge/source.sh
export
```
What does it show for homebridge version ?

**Comment by pasqualito79** [comment]
the old one ;-)

<img width="664" height="595" alt="Image" src="https://github.com/user-attachments/assets/8c387f79-9759-4f96-8f1b-f1fd70344490" />

**Comment by pasqualito79** [comment]
btw, in dark mode, the info page is unreadable:

<img width="787" height="903" alt="Image" src="https://github.com/user-attachments/assets/b1ab1928-3544-4ae1-a10d-188c1ce3cc99" />

**Comment by NorthernMan54** [comment]
A bit of a Duuh moment for me here - Found the issue and fixed it.  https://github.com/homebridge/docker-homebridge/commit/bd304967c47386e2490bfe60fbe1a9b435440474

Next release will resolve.
