### ISSUE TITLE
Permission errors on Raspberry Pi

### ISSUE THREAD

**Issue by jasmas** [oznu/docker-homebridge#97]
The latest update is causing permission errors on Raspberry Pi when updating or deleting plugins. I also noticed that the file containing user information is written as root in spite of the PUID and PGID being set to 1000 as the pi user for the container.

**Comment by oznu** [comment]
The permissions on all files in `/homebridge` are fixed everytime homebridge (the process, not necessarily the entire container) is restarted.

https://github.com/oznu/docker-homebridge/blob/master/root/etc/services.d/homebridge/run#L4

Is this not working for you? If not, I'll need some logs showing the entire container startup and the errors your getting.

**Comment by jasmas** [comment]
I'm thinking it had to have been a docker issue since it was somehow creating the files as root. All the node_modules were installing as root too. I tried deleting and recreating the container and even wiping out the config folder several times and the issue persisted, but when I rebooted the Pi now all seems well.
